# File: services/api-gateway-service/src/main/resources/application-prod.yml
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service  # Service discovery
        - id: video-service
          uri: lb://video-service
        - id: analytics-service
          uri: lb://analytics-service

logging:
  level:
    root: WARN
    com.videoanalytics.gateway: INFO

security:
  require-ssl: true  # Force HTTPS in production