# File: services/api-gateway-service/src/main/resources/application-test.yml
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081  # Docker container names
        - id: video-service
          uri: http://video-service:8082
        - id: analytics-service
          uri: http://analytics-service:8083

logging:
  level:
    root: INFO
    com.videoanalytics.gateway: DEBUG